name: FULL STACK DEVELOPMENT

on:
  push:
    branches: [main, dev]
    paths:
      - "code/frontend/**"
  pull_request:
    branches: [main, dev]
    paths:
      - "code/frontend/**"

jobs:
  frontend:
    name: Build Frontend
    runs-on: First

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


        # since it also uses yarn, npm, vite etc, we have to use the same node version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            code/frontend/node_modules
          key: ${{ runner.os }}-frontend-yarn-${{ hashFiles('code/frontend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-frontend-yarn-

      - name: Install Frontend Dependencies
        run: |
          cd code/frontend
          yarn install

      - name: Build Frontend
        run: |
          cd code/frontend
          yarn build
