
name: FULL STACK DEVELOPMENT

on:
  push:
    branches: [main, dev]
    paths:
      - "code/backend1/**"
      - "code/backend2/**"
  pull_request:
    branches: [main, dev]
    paths:
      - "code/backend1/**"
      - "code/backend2/**"

jobs:
  backend:
    name: Build Backend
    runs-on: second
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # yarn caching requires setting up nodejs with correct version, while coding we have used version 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Caching backend1 dependencies
      - name: Cache of backend1 
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
          # following is the convention to make the key unique.
          # os + context + package manager + hashfile
          key: ${{ runner.os }}-backend1-yarn-${{ hashFiles('code/backend1/yarn.lock') }}

      - name: Install backend1 dependencies
        run: |
          cd code/backend1
          yarn install

      - name: Build Backend1
        run: |
          cd code/backend1
          yarn build

      # Caching backend2 dependencies
      - name: Cache of backend2 
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
          key: ${{ runner.os }}-backend2-yarn-${{ hashFiles('code/backend2/yarn.lock') }}

      - name: Install backend2 dependencies
        run: |
          cd code/backend2
          yarn install

      - name: Build Backend2
        run: |
          cd code/backend2
          yarn build
