name: FULL STACK DEVELOPMENT

on:
    push:
        branches: [main, dev]
        paths:
            - "code/frontend/**"
    pull_request:
        branches: [main, dev]
        paths:
            - "code/frontend/**"

jobs:
    frontend:
        name: Build Frontend
        runs-on: [First]
        steps:
            - name: Checkout Code
              uses: actions/check out@v4

            - name: Install Frontend Dependencies
              run: |
                  cd code/frontend
                  yarn install

            - name: Build Frontend
              run: |
                  cd code/frontend
                  yarn build

    