name: FULL STACK DEVELOPMENT

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    frontend:
        name: Build Frontend
        runs-on: [First]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Frontend Dependencies
              run: |
                  cd code/frontend
                  yarn install

            - name: Build Frontend
              run: |
                  cd code/frontend
                  yarn build

    backend:
        name: Build Backend
        runs-on: [second]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Backend Dependencies
              run: |
                  cd code/backend1
                  yarn install

            - name: Build Backend1
              run: |
                  cd code/backend1
                  yarn build

            - name: Install Backend2 Dependencies
              run: |
                  cd code/backend2
                  yarn install

            - name: Build Backend2
              run: |
                  cd code/backend2
                  yarn build
