name: FULL STACK DEVELOPMENT

on:
    push:
        branches: [main, dev]
        paths:
            - "code/backend1/**"
            - "code/backend2/**"
    pull_request:
        branches: [main, dev]
        paths:
            - "code/backend1/**"
            - "code/backend2/**"

jobs:
    backend:
        name: Build Backend
        runs-on: second
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Backend1 Dependencies
              run: |
                  cd code/backend1
                  yarn install

            - name: Build Backend1
              run: |
                  cd code/backend1
                  yarn build

            - name: Install Backend2 Dependencies
              run: |
                  cd code/backend2
                  yarn install

            - name: Build Backend2
              run: |
                  cd code/backend2
                  yarn build
